Add icmp-prohibit to port blocking module

diff --git a/guestfiles/proxy_cli/proxy_modules/port/port b/guestfiles/proxy_cli/proxy_modules/port/port
--- a/guestfiles/proxy_cli/proxy_modules/port/port
+++ b/guestfiles/proxy_cli/proxy_modules/port/port
@@ -23,9 +23,10 @@ usage()
   echo "ARGUMENTS"
   echo "  single                A single port. E.g. 8080"
   echo "  rangeStart:rangeEnd   A range of ports. E.g. 560:570"
-  echo "  action                Action to take."
-  echo "                         - drop   drop packet"
-  echo "                         - rst    drop and send TCP RST"
+  echo "  action                Action to take:"
+  echo "                         drop     drop packet"
+  echo "                         rst      drop and send TCP RST"
+  echo "                         icmp     drop and send icmp-admin-prohibited" 
   echo "OPTIONS"
   echo "  flush                 Flush active rules."
   echo "  show                  Show active rules."
@@ -84,6 +85,24 @@ case $1 in
       elif [[ $1 =~ $PORT_RANGE ]]; then
         iptables -A OUTPUT -p tcp -m multiport --dports $1 -m comment --comment "$COMMENT" -j REJECT --reject-with tcp-reset
         ip6tables -A OUTPUT -p tcp -m multiport --dports $1 -m comment --comment "$COMMENT" -j REJECT --reject-with tcp-reset
+      else
+        echo "Invalid port or port range."
+        exit 1
+      fi
+    elif [[ $2 == "icmp" ]]
+    then
+      if [[ $1 =~ $SINGLE_PORT ]]; then
+        iptables -A OUTPUT -p tcp --dport $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp-admin-prohibited
+        iptables -A OUTPUT -p udp --dport $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp-admin-prohibited
+        ip6tables -A OUTPUT -p tcp --dport $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp6-adm-prohibited
+        ip6tables -A OUTPUT -p udp --dport $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp6-adm-prohibited
+        
+      elif [[ $1 =~ $PORT_RANGE ]]; then
+        iptables -A OUTPUT -p tcp -m multiport --dports $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp-admin-prohibited
+        iptables -A OUTPUT -p udp -m multiport --dports $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp-admin-prohibited
+        ip6tables -A OUTPUT -p tcp -m multiport --dports $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp6-adm-prohibited
+        ip6tables -A OUTPUT -p udp -m multiport --dports $1 -m comment --comment "$COMMENT" -j REJECT --reject-with icmp6-adm-prohibited
+
       else
         echo "Invalid port or port range."
         exit 1
